steps:
- id: "GO Install"
  name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['GOPATH=src/soma']

- id: "Executar o teste unitário"
  name: 'gcr.io/cloud-builders/go'
  args: ['run','test']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/desafio-ci', '.']

images:
- 'gcr.io/$PROJECT_ID/desafio-ci'
